 - name: 'Install firewalld'
   yum: 
       name: firewalld 
       state: latest
   become: true

 - name: 'Firewalld start'
   service: name=firewalld state=started enabled=yes

 - name: 'Add firewalld port'
   command: firewall-cmd --permanent --zone=public --add-port=3306/tcp

 - name: 'firewalld reload'
   command: firewall-cmd --reload
 
 - name: 'Install httpd php php-mysql'
   yum:
       name: '{{item}}'
       state: present
   loop:
       - httpd
       - php
       - php-mysql
   when: '"httpd" not in ansible_facts.packages'

 - name: 'Add port 80 to firewalld'
   command: firewall-cmd --permanent --zone=public --add-port=80/tcp

 - name: 'firewalld reload again'
   command: firewall-cmd --reload
            
 - name: 'Change httpd.conf file' 
   shell: sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf
           
 - name: 'Start and enable httpd'
   service: 
       name: httpd 
       state: started
       enabled: yes
          
 - name: 'Installing git'
   yum:
       name: git
   become: true