- name: 'Install mariadb'
  yum: 
    name: mariadb-server
    state: latest
  become: true
          
- name: 'mariadb start'
  service: name=mariadb state=started enabled=yes
  
- name: 'installing python-3 mysql libraries'
  yum: name=MySQL-python state=present

- name: 'create mariadb database'
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL,GRANT'
    state: present

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False